config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:index, :new, :create]
  end
  resources :reviews, only: [:edit, :update, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: ["chinese", "italian", "japanese", "french", "belgian"]
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates_numericality_of :rating
  validates_inclusion_of :rating, in: 0..5
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base  
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:success] = "Successfully added!"
      redirect_to @restaurant
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      flash[:success] = "Successfully added!"
      redirect_to @restaurant
    else
      flash[:error] = "Something went wrong..."
      render 'new'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<h1>My restaurants</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
    <% if restaurant.completed == true %>
      <li>✅<%= link_to restaurant.title, restaurant_path(restaurant.id)  %>---<%= link_to "Delete? 🧺",
            restaurant_path(restaurant.id),
            method: :delete,
            data: { confirm: "Are you sure?" } %></li>
    <% else %>
      <li>⬜<%= link_to restaurant.title, restaurant_path(restaurant.id) %>---<%= link_to "Delete? 🧺",
            restaurant_path(restaurant.id),
            method: :delete,
            data: { confirm: "Are you sure?" } %></li>
    <% end %>
  <% end %>
</ul>

app/views/restaurants/restaurants.html.erb
<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone_number %></p>

<%= link_to 'go back', restaurant_path %>

app/views/reviews/index.html.erb
<h1>Reviews</h1>
<h1>My reviews</h1>
<ul>
  <% @reviews.each do |review| %>
    <% if review.completed == true %>
      <li>✅<%= link_to review.title, restaurant_reviews_path(review.id)  %>---<%= link_to "Delete? 🧺",
            review_path(review.id),
            method: :delete,
            data: { confirm: "Are you sure?" } %></li>
    <% else %>
      <li>⬜<%= link_to review.title, restaurant_reviews_path(review.id) %>---<%= link_to "Delete? 🧺",
            review_path(review.id),
            method: :delete,
            data: { confirm: "Are you sure?" } %></li>
    <% end %>
  <% end %>
</ul>

app/views/reviews/reviews.html.erb
<h2><%= @review.content %></h2>
<p><%= @review.rating %></p>

<%= link_to 'go back', review_path %>
<%= link_to 'edit review', edit_review_path %>